import base64
from openai import OpenAI
from google.genai import types
from google.adk.tools.tool_context import ToolContext
import litellm

# Initialize the NATIVE client for the tool to bypass LiteLLM restrictions
client = OpenAI()


async def generate_and_save_images(tool_context: ToolContext):
    draft = tool_context.state.get("story_book_draft")

    if not draft or "pages" not in draft:
        return {"status": "error", "message": "Story draft not found in state."}

    story_id = draft.get("story_id", "default_id")
    pages = draft["pages"]

    existing_artifacts = await tool_context.list_artifacts()
    generated_images = []

    for page in pages:
        page_num = page.get("page_number")
        visual_desc = page.get("visual_description")
        filename = f"{story_id}_page_{page_num}_image.png"

        # Cache check
        if filename in existing_artifacts:
            print(f"[DEBUG] Image {filename} cached. Skipping.")
            generated_images.append(
                {"page_number": page_num, "filename": filename, "status": "cached"}
            )
            continue

        print(f"[DEBUG] Generating image for page {page_num} natively...")
        try:
            # Using your exact native OpenAI client logic
            image = client.images.generate(
                model="gpt-image-1",
                prompt=f"Whimsical Children's Book Illustration style. {visual_desc}",
                n=1,
                quality="low",
                moderation="low",
                output_format="jpeg",
                background="opaque",
                size="1024x1024",
            )

            # Decode the base64 string directly from the response
            image_bytes = base64.b64decode(image.data[0].b64_json)

            artifact = types.Part(
                inline_data=types.Blob(
                    mime_type="image/jpeg",
                    data=image_bytes,
                )
            )

            await tool_context.save_artifact(
                filename=filename,
                artifact=artifact,
            )

            generated_images.append(
                {"page_number": page_num, "filename": filename, "status": "generated"}
            )

        except Exception as e:
            print(f"[ERROR] Failed to generate image for page {page_num}: {e}")
            generated_images.append(
                {"page_number": page_num, "status": f"error: {str(e)}"}
            )

    # Return OUTSIDE the for-loop so it processes all 5 pages
    return {
        "total_processed": len(generated_images),
        "details": generated_images,
        "status": "complete",
    }


### 수업에 나온 방식으로 작성한 코드
# async def generate_and_save_images(tool_context: ToolContext):
#     """
#     Reads the story draft from state, checks for existing artifacts,
#     and generates/saves missing images to the ADK Artifact store.
#     """
#     # 1. Pull the structured data generated by the Story Writer
#     draft = tool_context.state.get("story_book_draft")

#     if not draft or "pages" not in draft:
#         return {"status": "error", "message": "Story draft not found in state."}

#     pages = draft["pages"]

#     # 2. Get currently saved artifacts to prevent redundant generation
#     existing_artifacts = await tool_context.list_artifacts()
#     generated_images = []

#     for page in pages:
#         page_num = page.get("page_number")
#         visual_desc = page.get("visual_description")
#         filename = f"page_{page_num}_image.png"

#         # CACHE CHECK: If it exists, skip generation to save tokens
#         if filename in existing_artifacts:
#             print(f"[DEBUG] Image {filename} already exists. Skipping generation.")
#             generated_images.append(
#                 {"page_number": page_num, "filename": filename, "status": "cached"}
#             )
#             continue

#         print(f"[DEBUG] Generating image for page {page_num}...")
#         try:
#             # Generate image and request base64 format directly to avoid downloading via requests
#             response = litellm.image_generation(
#                 prompt=f"Whimsical Children's Book Illustration style. {visual_desc}",
#                 model="gpt-image-1",  # "gpt-image-1", "dall-e-3"
#                 size="256x256",
#                 response_format="b64_json",
#             )

#             # Decode the base64 string
#             image_bytes = base64.b64decode(response.data[0].b64_json)

#             # Create ADK Artifact Blob
#             artifact = types.Part(
#                 inline_data=types.Blob(
#                     mime_type="image/png",
#                     data=image_bytes,
#                 )
#             )

#             # Save to ADK Artifact Store
#             await tool_context.save_artifact(
#                 filename=filename,
#                 artifact=artifact,
#             )

#             generated_images.append(
#                 {"page_number": page_num, "filename": filename, "status": "generated"}
#             )

#         except Exception as e:
#             print(f"[ERROR] Failed to generate image for page {page_num}: {e}")
#             generated_images.append(
#                 {"page_number": page_num, "status": f"error: {str(e)}"}
#             )

#     # RETURN OUTSIDE THE FOR-LOOP (Fixed from your snippet)
#     return {
#         "total_processed": len(generated_images),
#         "details": generated_images,
#         "status": "complete",
#     }
